### ISSUE TITLE
Benchmark Gemma models

### ISSUE THREAD

**Issue by vmakarov-pistoia** [biocypher/biochatter#138]
Gemma model family
https://huggingface.co/google/gemma-7b
https://huggingface.co/google/gemma-2b
https://huggingface.co/google/codegemma-7b
https://huggingface.co/google/codegemma-2b

see also https://www.kaggle.com/models/google/gemma

**Comment by slobentanzer** [comment]
Thanks, @vmakarov-pistoia.
Gemma chat is available in Xinference standard models as `gemma-it` I believe (https://inference.readthedocs.io/en/latest/models/builtin/llm/gemma-it.html), so this should be quick. I didn't see codegemma though, that may take a little longer.

**Comment by slobentanzer** [comment]
I have to note that #134 from @matthijsz asks for overlapping models, we should probably only have one issue for Gemma.

**Comment by slobentanzer** [comment]
Closing this; Gemma models are accounted for by #134
