### ISSUE TITLE
Create `anndata` function calling modules

### ISSUE THREAD

**Issue by noahbruderer** [biocypher/biochatter#224]
This issue is to create a module in the API agent that can generate function calls for [anndata](https://anndata.readthedocs.io/en/stable/api.html) package, starting with combining, reading and filtering.

**Comment by anisdismail** [comment]
Done in https://github.com/biocypher/biochatter/pull/229
- develop a starter for pydantic classes for the anndata reader classes
- develop a tools calling starter code for binding multiple classes
 
Next steps needed: 
- modify the query builder
- modify unit tests for the new structure
- develop a abtract class parser for the pydantic class  

Next sprint: 
- extend it to filtering, mapping and concatenating
