### ISSUE TITLE
Vector DB: connection_args not used in `connect()` method

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter#45]
When we instantiate a DocumentEmbedder with connection_args, why are they not used in the `connect()` method to determine IP and port?

**Comment by fengsh27** [comment]
@slobentanzer Good catch, initially, the `connect()` function was being called within the constructor, and `connection_args` was being passed as arguments to `connect()`. However, at some point, it became necessary to call `connect()` independently. Unfortunately, I forgot to update the parameters accordingly.

I'll fix it in next submission. Thank you for bring this to my attention.

**Comment by slobentanzer** [comment]
Great, thanks. Does not seem like a huge deal, but I wanted to ask first. :)
