### ISSUE TITLE
Data tables to show benchmark results on docs page

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biochatter#93]
https://squidfunk.github.io/mkdocs-material/reference/data-tables/#column-alignment-left

**Comment by nilskre** [comment]
Loading the result csv files can be done by using the [mkdocs-table-reader-plugin](https://timvink.github.io/mkdocs-table-reader-plugin/).
tbd: is there also a plugin to load the data from a database?

**Comment by nilskre** [comment]
ToDo: Overview table with models on y axis and tasks on x axis
